import { LivrableEntry } from '@/types/livrable';

export const ALL_SEED_LIVRABLES: LivrableEntry[] = [
    {
        id: 'livrable-dat-microservices-nextjs',
        title: 'Dossier d\'Architecture Technique (DAT) : Plateforme SaaS Multi-Tenant',
        category: 'DAT',
        categoryLabel: 'Dossier d\'Architecture Technique',
        promo: 'A3',
        specialty: 'Informatique',
        year: '2026',
        authorName: 'Alexandre M. (FISA A3)',
        isAnonymous: false,
        publishedAt: '2026-01-20T10:00:00.000Z',
        viewsCount: 684,
        downloadCount: 428,
        summary: 'Document complet de spécifications techniques : modélisation C4 (Context, Container, Component), diagrammes de flux de données, dimensionnement infrastructure, API contracts OpenAPI et matrice de choix technologiques.',
        keySections: [
            '1. Contexte, Objectifs & Enjeux Métier',
            '2. Modélisation C4 & Cartographie Applicative',
            '3. Choix Technologiques & Arbre de Décision (ADR)',
            '4. Sécurité, Chiffrement & Authentification OAuth/JWT',
            '5. Stratégie de Résilience & Dimensionnement Cloud'
        ],
        tags: ['Diagrammes C4', 'API REST', 'Next.js', 'PostgreSQL', 'Docker', 'OAuth 2.0'],
        gradeHint: 'Évaluation : Grade A • Validé jury CESI',
        format: 'Markdown + PDF + Schémas draw.io'
    },
    {
        id: 'livrable-cdcf-application-mobile-iot',
        title: 'Cahier des Charges Fonctionnel & Technique (CDCF) : Système Connecté IoT',
        category: 'CDC',
        categoryLabel: 'Cahier des Charges',
        promo: 'A3',
        specialty: 'Systèmes Embarqués',
        year: '2025',
        authorName: 'Nicolas M. (A3)',
        isAnonymous: false,
        publishedAt: '2025-11-12T14:00:00.000Z',
        viewsCount: 512,
        downloadCount: 382,
        summary: 'Cahier des charges complet pour projet de bloc : expression détaillée du besoin, personas utilisateurs, matrice MoSCoW, 25 User Stories avec critères d\'acceptation Gherkin et budget prévisionnel.',
        keySections: [
            '1. Périmètre & Cartographie des Parties Prenantes',
            '2. Personas & Parcours Utilisateurs (User Journeys)',
            '3. Matrice d\'Exigences & Priorisation MoSCoW',
            '4. Backlog de 25 User Stories (Format Gherkin)',
            '5. Contraintes Réglementaires RGPD & Sécurité'
        ],
        tags: ['Méthode Agile', 'MoSCoW', 'User Stories', 'Gherkin', 'Personas', 'RGPD'],
        gradeHint: 'Évaluation : Grade A • Recommandé par tuteurs',
        format: 'PDF + Template Word / Google Docs'
    },
    {
        id: 'livrable-audit-securite-pentest-iso27001',
        title: 'Rapport d\'Audit de Sécurité des Systèmes d\'Information & Pentest Web',
        category: 'AUDIT',
        categoryLabel: 'Rapport d\'Audit & Pentest',
        promo: 'A4',
        specialty: 'Informatique',
        year: '2025',
        authorName: 'Sarah B. (A4)',
        isAnonymous: false,
        publishedAt: '2025-12-01T16:30:00.000Z',
        viewsCount: 420,
        downloadCount: 315,
        summary: 'Rapport technique et exécutif d\'audit de vulnérabilités selon le standard OWASP Top 10 et ISO 27001 : cartographie de surface d\'attaque, preuves de concept (PoC), matrice des risques CVSS v3 et plan de remédiation.',
        keySections: [
            '1. Synthèse Exécutive à Destination de la Direction',
            '2. Périmètre d\'Audit & Méthodologie OWASP',
            '3. Tableau Synthétique des Vulnérabilités Détectées',
            '4. Preuves de Concept Détaillées (PoC) & Scores CVSS',
            '5. Plan d\'Action & Mesures de Durcissement Prioritaires'
        ],
        tags: ['OWASP Top 10', 'CVSS v3.1', 'Nmap / Burp Suite', 'ISO 27001', 'Hardening', 'Réseaux'],
        gradeHint: 'Évaluation : Grade A • Validé bloc Cyber',
        format: 'Rapport PDF Professionnel + Grille CVSS Excel'
    },
    {
        id: 'livrable-soutenance-slides-pitch-guide',
        title: 'Support & Diaporama de Soutenance Finale de Projet (Slides PPTX + Script)',
        category: 'SOUTENANCE',
        categoryLabel: 'Support de Soutenance',
        promo: 'A3',
        specialty: 'Généraliste',
        year: '2026',
        authorName: 'Lucas B. (A3)',
        isAnonymous: false,
        publishedAt: '2026-01-15T09:00:00.000Z',
        viewsCount: 890,
        downloadCount: 654,
        summary: 'Trame de présentation officielle pour soutenance de projet de bloc CESI (20 min de présentation + 10 min de questions) : 18 slides épurées, guide de posture d\'ingénieur, script minuté et réponses types aux questions pièges.',
        keySections: [
            '1. Slide Contexte, Problématique & Proposition de Valeur',
            '2. Démonstration Technique en Direct (Live Demo Checklist)',
            '3. Architecture & Choix Technologiques Clés',
            '4. Bilan de Gestion de Projet (Burndown Chart & Vélocité)',
            '5. Retex d\'Équipe, Limites & Perspectives d\'Évolution'
        ],
        tags: ['Template PPTX', 'Pitch Deck', 'Grille d\'Évaluation CESI', 'Chronométrage 20min', 'Communication'],
        gradeHint: 'Évaluation : Grade A • Félicitations du jury',
        format: 'PowerPoint .pptx + Guide PDF + Script de parole'
    },
    {
        id: 'livrable-bdd-mcd-mld-mpd-sql',
        title: 'Dossier de Conception Bases de Données (MCD, MLD, MPD & Scripts SQL)',
        category: 'BDD',
        categoryLabel: 'Dossier de Conception BDD',
        promo: 'A2',
        specialty: 'Informatique',
        year: '2025',
        authorName: 'Camille D. (A2)',
        isAnonymous: false,
        publishedAt: '2025-05-18T11:20:00.000Z',
        viewsCount: 395,
        downloadCount: 298,
        summary: 'Dossier complet de modélisation relationnelle Merise & UML : dictionnaire de données, règles de gestion, schémas entité-association, validation en 3NF/BCNF, scripts DDL PostgreSQL et procédures stockées.',
        keySections: [
            '1. Dictionnaire des Données & Règles de Gestion',
            '2. Modèle Conceptuel des Données (MCD) & Cardinalités',
            '3. Modèle Logique des Données (MLD) & Normalisation',
            '4. Script SQL DDL de Création avec Contraintes & Clés',
            '5. Vues Matérialisées, Index B-Tree & Transactions ACID'
        ],
        tags: ['Merise', 'MCD / MLD', 'PostgreSQL', 'Normalisation 3NF', 'Indexation SQL', 'DDL / DML'],
        gradeHint: 'Évaluation : Grade A • Validé bloc BDD',
        format: 'PDF + Scripts .sql + Modèle Looping/DBDesigner'
    },
    {
        id: 'livrable-btp-dossier-technique-bim',
        title: 'Dossier Technique & Modélisation BIM : Ouvrage d\'Art & Structure Béton',
        category: 'DAT',
        categoryLabel: 'Dossier d\'Architecture & BIM',
        promo: 'A4',
        specialty: 'BTP & Génie Civil',
        year: '2026',
        authorName: 'Julien L. (A4)',
        isAnonymous: false,
        publishedAt: '2026-02-01T15:00:00.000Z',
        viewsCount: 280,
        downloadCount: 210,
        summary: 'Dossier d\'études d\'exécution et maquette BIM niveau LOD 350 : calculs de ferraillage selon Eurocode 2, notes de calculs géotechniques et planification 4D de chantier.',
        keySections: [
            '1. Contexte Géotechnique & Hypothèses de Chargement',
            '2. Modélisation Maquette Numérique BIM (Revit)',
            '3. Notes de Calculs Eurocode 2 & Ferraillage',
            '4. Plan d\'Assurance Qualité & Sécurité de Chantier',
            '5. Bilan Carbone & Analyse du Cycle de Vie'
        ],
        tags: ['BIM', 'Revit', 'Eurocodes', 'Génie Civil', 'Béton Armé', 'LOD 350'],
        gradeHint: 'Évaluation : Grade A • Mention excellence',
        format: 'PDF + Maquette IFC + Notes de calculs Excel'
    }
];
